//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KonKhayHoi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenditure
    {
        public int EID { get; set; }
        public string E_date { get; set; }
        public string E_list { get; set; }
        public Nullable<int> amount { get; set; }
        public string payor { get; set; }
        public string note { get; set; }
        public Nullable<int> CID { get; set; }
    
        public virtual Circulation Circulation { get; set; }
    }
}
