//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KonKhayHoi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Farm()
        {
            this.Circulations = new HashSet<Circulation>();
        }
    
        public int FID { get; set; }
        public string F_name { get; set; }
        public string F_tel { get; set; }
        public string dateStart { get; set; }
        public string MonthOfSale { get; set; }
        public string F_no { get; set; }
        public string F_subD { get; set; }
        public string F_sub { get; set; }
        public string F_ProV { get; set; }
        public Nullable<int> Invest { get; set; }
        public string AID { get; set; }
    
        public virtual admin admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Circulation> Circulations { get; set; }
    }
}
