//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KonKhayHoi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class last
    {
        public int no { get; set; }
        public Nullable<int> lastA { get; set; }
        public Nullable<int> lastP { get; set; }
        public Nullable<int> lastS { get; set; }
    }
}
