//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KonKhayHoi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KonKhayHoiEntities : DbContext
    {
        public KonKhayHoiEntities()
            : base("name=KonKhayHoiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<Circulation> Circulations { get; set; }
        public virtual DbSet<Expenditure> Expenditures { get; set; }
        public virtual DbSet<Farm> Farms { get; set; }
        public virtual DbSet<last> lasts { get; set; }
        public virtual DbSet<Partner> Partners { get; set; }
        public virtual DbSet<Revenue> Revenues { get; set; }
        public virtual DbSet<Shop> Shops { get; set; }
    }
}
