//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KonKhayHoi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        public string PID { get; set; }
        public string P_name { get; set; }
        public string P_lastname { get; set; }
        public string P_tel { get; set; }
        public string P_pass { get; set; }
        public Nullable<int> P_investment { get; set; }
        public string P_no { get; set; }
        public string P_subD { get; set; }
        public string P_sub { get; set; }
        public string P_ProV { get; set; }
        public string AID { get; set; }
        public Nullable<int> Invest { get; set; }
    
        public virtual admin admin { get; set; }
    }
}
