//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KonKhayHoi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        public string SID { get; set; }
        public string Name { get; set; }
        public string S_name { get; set; }
        public string S_lastname { get; set; }
        public string S_tel { get; set; }
        public Nullable<int> purchasedAmount { get; set; }
        public string S_pass { get; set; }
        public string S_no { get; set; }
        public string S_subD { get; set; }
        public string S_sub { get; set; }
        public string S_ProV { get; set; }
        public Nullable<int> state { get; set; }
    }
}
